Minimal firewall rules

diff --git a/scripts/firewall-on b/scripts/firewall-on
--- a/scripts/firewall-on
+++ b/scripts/firewall-on
@@ -45,8 +45,8 @@ iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
 echo " * Allowing loopback devices"
 iptables -A INPUT -i lo -j ACCEPT
 
-echo " * Drop all traffic with an INVALID state match"
-iptables -A INPUT -m conntrack --ctstate INVALID -j DROP
+#echo " * Drop all traffic with an INVALID state match"
+#iptables -A INPUT -m conntrack --ctstate INVALID -j DROP
 
 echo " * Allowing ping responses"
 iptables -A INPUT -p icmp --icmp-type 8 -m conntrack --ctstate NEW -j ACCEPT
@@ -55,22 +55,25 @@ echo " * Setting TCP and UDP chains"
 iptables -A INPUT -p udp -m conntrack --ctstate NEW -j UDP
 iptables -A INPUT -p tcp --syn -m conntrack --ctstate NEW -j TCP
 
-echo " * Prevent SYN scan attack for TCP"
-iptables -I TCP -p tcp -m recent --update --rsource --seconds 60 --name TCP-PORTSCAN -j REJECT --reject-with tcp-reset
-iptables -A INPUT -p tcp -m recent --set --rsource --name TCP-PORTSCAN -j REJECT --reject-with tcp-reset
+#echo " * Prevent SYN scan attack for TCP"
+#iptables -I TCP -p tcp -m recent --update --rsource --seconds 60 --name TCP-PORTSCAN -j REJECT --reject-with tcp-reset
+#iptables -A INPUT -p tcp -m recent --set --rsource --name TCP-PORTSCAN -j REJECT --reject-with tcp-reset
 
-echo " * Prevent SYN scan attack for UDP"
-iptables -I UDP -p udp -m recent --update --rsource --seconds 60 --name UDP-PORTSCAN -j REJECT --reject-with icmp-port-unreachable
-iptables -A INPUT -p udp -m recent --set --rsource --name UDP-PORTSCAN -j REJECT --reject-with icmp-port-unreachable
+#echo " * Prevent SYN scan attack for UDP"
+#iptables -I UDP -p udp -m recent --update --rsource --seconds 60 --name UDP-PORTSCAN -j REJECT --reject-with icmp-port-unreachable
+#iptables -A INPUT -p udp -m recent --set --rsource --name UDP-PORTSCAN -j REJECT --reject-with icmp-port-unreachable
 
-echo " * Rejecting all other traffic"
-iptables -A INPUT -j REJECT --reject-with icmp-proto-unreachable
+#echo " * Rejecting all other traffic"
+#iptables -A INPUT -j REJECT --reject-with icmp-proto-unreachable
 
 echo " * Allowing wireguard on port 51820"
 iptables -A UDP -p udp --dport 51820 -j ACCEPT
 
 echo " * Allowing http on port 80"
 iptables -A TCP -p tcp --dport 80  -j ACCEPT
+
+#echo " * Allowing http on port 22"
+#iptables -A TCP -p tcp --dport 22  -j ACCEPT
  
 echo " * Allowing https on port 443"
 iptables -A TCP -p tcp --dport 443 -j ACCEPT
@@ -82,28 +85,28 @@ iptables -A TCP -p tcp --dport 443 -j ACCEPT
 echo " * SAVING RULES"
 iptables-save -f /etc/iptables/iptables.rules
 
-cat << EOF > /etc/iptables/ip6tables.rules
+#cat << EOF > /etc/iptables/ip6tables.rules
 # Generated by ip6tables-save v1.8.2 on Sat Apr 20 10:53:41 2019
-*filter
-:INPUT DROP [0:0]
-:FORWARD DROP [0:0]
-:OUTPUT ACCEPT [0:0]
-:TCP - [0:0]
-:UDP - [0:0]
--A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
--A INPUT -i lo -j ACCEPT
--A INPUT -m conntrack --ctstate INVALID -j DROP
--A INPUT -s fe80::/10 -p ipv6-icmp -j ACCEPT
--A INPUT -p udp --sport 547 --dport 546 -j ACCEPT
--A INPUT -p udp -m conntrack --ctstate NEW -j UDP
--A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j TCP
--A INPUT -p udp -j REJECT --reject-with icmp6-adm-prohibited
--A INPUT -p tcp -j REJECT --reject-with tcp-reset
--A INPUT -j REJECT --reject-with icmp6-adm-prohibited
--A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type 128 -m conntrack --ctstate NEW -j ACCEPT
-COMMIT
+#*filter
+#:INPUT DROP [0:0]
+#:FORWARD DROP [0:0]
+#:OUTPUT ACCEPT [0:0]
+#:TCP - [0:0]
+#:UDP - [0:0]
+#-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
+#-A INPUT -i lo -j ACCEPT
+#-A INPUT -m conntrack --ctstate INVALID -j DROP
+#-A INPUT -s fe80::/10 -p ipv6-icmp -j ACCEPT
+#-A INPUT -p udp --sport 547 --dport 546 -j ACCEPT
+#-A INPUT -p udp -m conntrack --ctstate NEW -j UDP
+#-A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j TCP
+#-A INPUT -p udp -j REJECT --reject-with icmp6-adm-prohibited
+#-A INPUT -p tcp -j REJECT --reject-with tcp-reset
+#-A INPUT -j REJECT --reject-with icmp6-adm-prohibited
+#-A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type 128 -m conntrack --ctstate NEW -j ACCEPT
+#COMMIT
 # Completed on Sat Apr 20 10:53:41 2019
-EOF
+#EOF
 echo " * STARTING IPTABLES AND IP6TABLES"
 systemctl enable --now iptables ip6tables
 echo "All set. Good luck!"
